'$schema' = 'https://starship.rs/config-schema.json'
add_newline = false
format = """
$username\
$hostname\
$sudo\
$kubernetes\
$container\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$deno\
$python\
$rust\
$pulumi\
$aws\
$azure\
$gcloud\
$cmd_duration\
$line_break\
$character
"""
right_format = '$time'

[aws]
symbol = 'aws '

[azure]
symbol = 'az '

[container]
format = '[$name]($style) '

[cmd_duration]
min_time = 0
show_milliseconds = true

[deno]
symbol = 'deno '
detect_extensions = ['js', 'mjs', 'ts', 'mts']
detect_files = ['package.json', 'deno.json', 'deno.jsonc', 'deno.lock']
detect_folders = ['node_modules']

[gcloud]
symbol = "gcp "

[git_branch]
symbol = 'branch '

[git_commit]
tag_symbol = ' tag '
tag_disabled = false

[git_metrics]
disabled = false

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'

[hostname]
ssh_only = false
aliases = { "Desktop" = "desk" }
format = '[$hostname]($style) in '

[kubernetes]
disabled = false
symbol = 'kube '
detect_files = ['k3s', 'k8s']

[package]
display_private = true
format = 'is [$version]($style) '

[python]
symbol = 'py '

[rust]
symbol = 'rs '

[sudo]
format = 'as [root](bold red)'
disabled = false

[time]
disabled = false

[username]
show_always = true
format = '[$user]($style):'